=== input-output-hk/hermes/hermes/schemas/hermes_app_metadata.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://github.com/input-output-hk/hermes/blob/main/hermes/schemas/hermes_app_metadata.schema.json",
    "title": "Application Metadata Schema",
    "description": "Metadata which defines a Hermes Application and is carried inside the Hermes Application Package.",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string",
            "title": "Application Metadata Schema Reference",
            "default": "https://github.com/input-output-hk/hermes/blob/main/hermes/schemas/hermes_app_metadata.schema.json",
            "pattern": "^(https://github.com/input-output-hk/hermes/blob/main/hermes/schemas/)|(.*/)hermes_app_metadata.schema.json$",
            "description": "Reference to the Application Metadata Schema.\nShould be to https:// this will be validated.\nLocal references are only to simplify development."
        },
        "name": {
            "type": "string",
            "title": "Application Name",
            "description": "Name of the Application"
        },
        "icon": {
            "type": "string",
            "title": "Application Icon",
            "description": "Path inside the Application to its Icon.\nMust be a `.svg` file.",
            "pattern": "^/.*\\.svg$"
        },
        "version": {
            "type": "string",
            "title": "Application Version",
            "description": "Version of the Application",
            "pattern": "^V[0-9]+\\.[0-9]+\\.[0-9]+( .*$)?"
        },
        "description": {
            "type": "string",
            "title": "Application Description",
            "description": "Short Description of the Application"
        },
        "about": {
            "type": "string",
            "title": "Application About",
            "description": "Long form Description of the Application"
        },
        "src": {
            "type": "array",
            "title": "Links to the source of this application.",
            "description": "Can be links to code repositories or the Authors website.\nSpecifying any `src` is Optional, however if defined, then these URLs must be reachable when the Application is packaged.",
            "items": {
                "type": "string",
                "format": "uri",
                "pattern": "^https://[^\\s/?#]+.[^\\s/?#]+(/[^\\s?#]*)?$"
            },
            "uniqueItems": true,
            "minItems": 1
        },
        "copyright": {
            "type": "array",
            "title": "Application Copyright",
            "description": "List of Copyright Notices/Claims over the Application.\nIf no copyright is claimed then there should be an explicit statement about the Application being in the public domain.",
            "items": {
                "type": "string"
            },
            "uniqueItems": true,
            "minItems": 1
        },
        "license": {
            "type": "array",
            "title": "Application License",
            "description": "List of Licenses/Claims over the Application.\nMust declare at least `spdx` or `file`, `note` is Optional.\nIf `file` is specified it must exist within the Package for the Application to be valid.",
            "uniqueItems": true,
            "minItems": 1,
            "items": {
                "type": "object",
                "additionalProperties": false,
                "minProperties": 1,
                "$comment": "Validation Should be one or both of `spdx` and `file` and `note` is optional.",
                "properties": {
                    "spdx": {
                        "type": "string",
                        "title": "License SPDX ID",
                        "description": "SPDX ID of the License.\nIn the case of proprietary or non SPDX licenses, do not specify a SPDX ID and just include a license file."
                    },
                    "file": {
                        "type": "string",
                        "title": "License File",
                        "description": "Path to the License File inside the Package.\nMust be a `.txt` file and it must exist at Package creation time.\nFile MUST be text, displayable using monospaced fonts and no line exceeds 80 characters.",
                        "pattern": "^/.*\\.txt$"
                    },
                    "note": {
                        "type": "string",
                        "title": "License Note",
                        "description": "Note about the License.\nFor Example: Could limit the license to a particular aspect of the Application or part of the code."
                    }
                }
            }
        },
        "build_date": {
            "type": "integer",
            "title": "Application Build Date",
            "description": "Unix Epoch Timestamp of when the Application was packaged or built."
        },
        "developer": {
            "type": "object",
            "title": "Application Developer",
            "additionalProperties": true,
            "properties": {
                "name": {
                    "type": "string",
                    "title": "Application Developer Name",
                    "description": "Name of the Developer"
                }
            },
            "required": [
                "name"
            ]
        },
        "resources": {
            "type": "object",
            "title": "Application Resources",
            "additionalProperties": false,
            "properties": {
                "file-storage": {
                    "type": "object",
                    "title": "Application File Storage Allocation",
                    "description": "File Storage Allocation of the Application",
                    "additionalProperties": false,
                    "properties": {
                        "minimum": {
                            "type": "integer",
                            "title": "Application Minimum File Storage",
                            "description": "Minimum File Storage of the Application.\nSize is in MegaBytes."
                        },
                        "requested": {
                            "type": "integer",
                            "title": "Application Requested File Storage",
                            "description": "Requested File Storage of the Application.\nSize is in MegaBytes."
                        },
                        "maximum": {
                            "type": "integer",
                            "title": "Application Maximum File Storage",
                            "description": "Maximum File Storage of the Application.\nSize is in MegaBytes."
                        }
                    },
                    "required": [
                        "minimum"
                    ]
                },
                "sqlite-db": {
                    "type": "object",
                    "title": "Application SQLite DB Storage Allocation",
                    "description": "SQLite DB Storage Allocation of the Application",
                    "additionalProperties": false,
                    "minProperties": 1,
                    "properties": {
                        "minimum": {
                            "type": "integer",
                            "title": "Application Minimum SQLite DB Storage",
                            "description": "Minimum SQLite DB Storage of the Application.\nSize is in MegaBytes."
                        },
                        "requested": {
                            "type": "integer",
                            "title": "Application Requested SQLite DB Storage",
                            "description": "Requested SQLite DB Storage of the Application.\nSize is in MegaBytes."
                        },
                        "maximum": {
                            "type": "integer",
                            "title": "Application Maximum SQLite DB Storage",
                            "description": "Maximum SQLite DB Storage of the Application.\nSize is in MegaBytes."
                        }
                    },
                    "required": [
                        "minimum"
                    ]
                }
            }
        },
        "permissions": {
            "type": "object",
            "title": "Application Permissions",
            "additionalProperties": false,
            "properties": {
                "admin": {
                    "type": "boolean",
                    "title": "Application requires Admin Privileges",
                    "description": "Does the application require Admin Privileges.",
                    "default": false
                }
            }
        }
    },
    "required": [
        "$schema",
        "name",
        "icon",
        "version",
        "description",
        "copyright",
        "license",
        "build_date"
    ]
}

=== input-output-hk/hermes/hermes/schemas/example/hermes_app_metadata.json
{
    "$schema": "../hermes_app_metadata.schema.json",
    "name": "Athena - Project Catalyst Voting",
    "icon": "/srv/www/icons/athena.svg",
    "version": "V2.7.3",
    "description": "Project Catalyst Inovation Platform",
    "about": "About Project Catalyst, long form.\nMulti line.",
    "src": [
        "https://github.com/input-output-hk/hermes",
        "https://github.com/input-output-hk/catalyst-voices"
    ],
    "copyright": [
        "Copyright â’¸ 2024, IOG Singapore."
    ],
    "license": [
        {
            "spdx": "Apache-2.0",
            "file": "/srv/data/apache2.txt",
            "note": "A note"
        },
        {
            "spdx": "MIT",
            "file": "/srv/data/mit.txt"
        },
        {
            "spdx": "Apache-2.0",
            "note": "A note"
        },
        {
            "file": "/srv/data/apache2.txt",
            "note": "A note"
        }
    ],
    "build_date": 1709041814,
    "developer": {
        "name": "IOG Singapore.",
        "contact": "Contact details.",
        "payment": "wallet address"
    },
    "resources": {
        "file-storage": {
            "minimum": 100,
            "requested": 300,
            "maximum": 1024
        },
        "sqlite-db": {
            "minimum": 1024,
            "requested": 4096,
            "maximum": 32768
        }
    },
    "permissions": {
        "admin": true
    }
}
