=== input-output-hk/hermes/hermes/schemas/hermes_module_manifest.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/input-output-hk/hermes/main/hermes/schemas/hermes_module_manifest.schema.json",
    "title": "Hermes Application WASM Component Module Manifest Schema",
    "description": "Defines the src packages which are used to build a Hermes WASM Component Module.",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string",
            "title": "Application Package Manifest Schema Reference",
            "default": "https://raw.githubusercontent.com/input-output-hk/hermes/main/hermes/schemas/hermes_module_manifest.schema.json",
            "pattern": "^(https://raw.githubusercontent.com/input-output-hk/hermes/main/hermes/schemas/)|(.*/)hermes_module_manifest.schema.json$",
            "description": "Reference to the Application Manifest Schema.\nShould be to https:// this will be validated.\nLocal references are only to simplify development."
        },
        "name": {
            "type": "string",
            "title": "Hermes Module Package name.",
            "description": "Name of the Hermes WASM Module Package with which it will be created.",
            "default": "module"
        },
        "metadata": {
            "title": "Hermes Module Metadata File",
            "description": "Link to the Hermes Module Metadata json file.\nWill be renamed to `metadata.json` inside the module.",
            "oneOf": [
                {
                    "type": "string",
                    "pattern": "^file://(/?([a-zA-Z0-9-_\\.]+))+\\.json$",
                    "format": "uri"
                },
                {
                    "type": "string"
                }
            ],
            "default": "metadata.json"
        },
        "component": {
            "title": "WASM Component File",
            "description": "Link to the Hermes Module WASM Component file.\nThis is a fully compiled and linked WASM Object file.\nWill be renamed to `module.wasm` inside the module.",
            "oneOf": [
                {
                    "type": "string",
                    "pattern": "^file://(/?([a-zA-Z0-9-_\\.]+))+\\.json$",
                    "format": "uri"
                },
                {
                    "type": "string"
                }
            ],
            "default": "module.wasm"
        },
        "config": {
            "type": "object",
            "title": "Application Module Config Object.",
            "description": "Object representing the Application Module Config File.",
            "properties": {
                "file": {
                    "title": "Application Module Config File Location",
                    "description": "Path to the WASM Component Library Module Config File.\nThis will be renamed to `config.json` inside the module.",
                    "oneOf": [
                        {
                            "type": "string",
                            "pattern": "^file://(/?([a-zA-Z0-9-_\\.]+))+\\.json$",
                            "format": "uri"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "schema": {
                    "title": "Application Module Config Schema Location",
                    "description": "Path to the WASM Component Module Config Schema File.\nThis will be renamed to `config.schema.json` inside the module.",
                    "oneOf": [
                        {
                            "type": "string",
                            "pattern": "^file://(/?([a-zA-Z0-9-_\\.]+))+\\.json$",
                            "format": "uri"
                        },
                        {
                            "type": "string"
                        }
                    ]
                }
            }
        },
        "settings": {
            "type": "object",
            "title": "Application Module Settings Object.",
            "description": "Object representing the Application Module Settings.",
            "properties": {
                "schema": {
                    "title": "Application Module Settings Schema Location",
                    "description": "Path to the WASM Component Module Settings Schema File.\nThis will be renamed to `settings.schema.json` inside the module.",
                    "oneOf": [
                        {
                            "type": "string",
                            "pattern": "^file://(/?([a-zA-Z0-9-_\\.]+))+\\.json$",
                            "format": "uri"
                        },
                        {
                            "type": "string"
                        }
                    ]
                }
            }
        },
        "share": {
            "title": "Application Module Share Dataset.",
            "description": "Path to the WASM Component Library Module Shareable Data.\nWill set the default data defined for the module itself.",
            "oneOf": [
                {
                    "type": "string",
                    "pattern": "^file://(/?([a-zA-Z0-9-_\\.]+))+\\.json$",
                    "format": "uri"
                },
                {
                    "type": "string"
                }
            ]
        }
    },
    "required": [
        "$schema"
    ]
}

=== input-output-hk/hermes/hermes/apps/athena/modules/stake-ada-indexer/lib/manifest_module.json
{
    "$schema": "https://raw.githubusercontent.com/input-output-hk/hermes/main/hermes/schemas/hermes_module_manifest.schema.json",
    "name": "staked_ada_indexer",
    "metadata": "metadata.json",
    "component": "staked_ada_indexer.wasm",
    "config": {
        "file": "config.json",
        "schema": "config.schema.json"
    },
    "settings": {
        "schema": "settings.schema.json"
    }
}

=== input-output-hk/hermes/hermes/apps/athena/manifest_module.json
{
    "$schema": "https://raw.githubusercontent.com/input-output-hk/hermes/main/hermes/schemas/hermes_module_manifest.schema.json",
    "name": "web2",
    "metadata": "metadata.json",
    "component": "http_proxy.wasm",
    "config": {
        "file": "config.json",
        "schema": "config.schema.json"
    },
    "settings": {
        "schema": "settings.schema.json"
    }
}

=== input-output-hk/hermes/hermes/apps/athena/modules/rbac-registration/lib/manifest_module.json
{
    "$schema": "https://raw.githubusercontent.com/input-output-hk/hermes/main/hermes/schemas/hermes_module_manifest.schema.json",
    "name": "rbac_registration",
    "metadata": "metadata.json",
    "component": "rbac_registration.wasm",
    "config": {
        "file": "config.json",
        "schema": "config.schema.json"
    },
    "settings": {
        "schema": "settings.schema.json"
    }
}

=== input-output-hk/hermes/hermes/bin/tests/integration/tests/utils/app_support_files/manifest_module.json
{
    "$schema": "https://raw.githubusercontent.com/input-output-hk/hermes/main/hermes/schemas/hermes_module_manifest.schema.json",
    "name": "test_module",
    "metadata": "metadata.json",
    "component": "test_component.wasm",
    "config": {
        "file": "config.json",
        "schema": "config.schema.json"
    },
    "settings": {
        "schema": "settings.schema.json"
    }
}

=== input-output-hk/hermes/hermes/apps/athena/modules/voting-index/lib/manifest_module.json
{
    "$schema": "https://raw.githubusercontent.com/input-output-hk/hermes/main/hermes/schemas/hermes_module_manifest.schema.json",
    "name": "voting_index",
    "metadata": "metadata.json",
    "component": "voting_index.wasm",
    "config": {
        "file": "config.json",
        "schema": "config.schema.json"
    },
    "settings": {
        "schema": "settings.schema.json"
    }
}

=== input-output-hk/hermes/hermes/apps/athena/modules/rbac-registration-indexer/lib/manifest_module.json
{
	"$schema": "https://raw.githubusercontent.com/input-output-hk/hermes/main/hermes/schemas/hermes_module_manifest.schema.json",
	"name": "rbac_registration_indexer",
	"metadata": "metadata.json",
	"component": "rbac_registration_indexer.wasm",
	"config": {
		"file": "config.json",
		"schema": "config.schema.json"
	},
	"settings": {
		"schema": "settings.schema.json"
	}
}

=== input-output-hk/hermes/hermes/apps/athena/modules/staked-ada/lib/manifest_module.json
{
  "$schema": "https://raw.githubusercontent.com/input-output-hk/hermes/main/hermes/schemas/hermes_module_manifest.schema.json",
  "name": "staked_ada",
  "metadata": "metadata.json",
  "component": "staked_ada.wasm",
  "config": {
    "file": "config.json",
    "schema": "config.schema.json"
  },
  "settings": {
    "schema": "settings.schema.json"
  }
}

=== input-output-hk/hermes/hermes/apps/athena/modules/db/lib/manifest_module.json
{
    "$schema": "https://raw.githubusercontent.com/input-output-hk/hermes/main/hermes/schemas/hermes_module_manifest.schema.json",
    "name": "db",
    "metadata": "metadata.json",
    "component": "db.wasm",
    "config": {
        "file": "config.json",
        "schema": "config.schema.json"
    },
    "settings": {
        "schema": "settings.schema.json"
    }
}
