=== input-output-hk/hermes/hermes/schemas/hermes_app_cose_author_payload.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/input-output-hk/hermes/main/hermes/schemas/hermes_app_cose_author_payload.schema.json",
    "title": "Hermes Application Author COSE Payload Schema",
    "description": "Defines the COSE signing payload. An application package specific information which should be cryptographically protected.",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "metadata": {
            "type": "string",
            "title": "Blake2b hash hex of metadata.json package file",
            "description": "A hex representation of the Blake2b hash of the metadata.json file inside the package.",
            "pattern": "^[0-9a-f]{64}$"
        },
        "icon": {
            "type": "string",
            "title": "Blake2b hash hex of icon.svg package file",
            "description": "A hex representation of the Blake2b hash of the icon.svg file inside the package.",
            "pattern": "^[0-9a-f]{64}$"
        },
        "modules": {
            "type": "array",
            "title": "Application Module Files Hashes",
            "description": "List of WASM Component Library Module Files Hashes.",
            "items": {
                "type": "object",
                "title": "Application WASM Module Package definition",
                "description": "Prepackaged Hermes WASM Component Module.",
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "type": "string",
                        "title": "Application WASM Module Name",
                        "description": "Name of the WASM Component Library Module.\nMust be unique within the Application."
                    },
                    "package": {
                        "type": "string",
                        "title": "Blake2b hash hex of the WASM module package author.cose signature bytes",
                        "description": "A hex representation of the Blake2b hash of of the WASM module package author.cose signature bytes.",
                        "pattern": "^[0-9a-f]{64}$"
                    },
                    "config": {
                        "type": "string",
                        "title": "Blake2b hash hex of replaced module's config.json package file",
                        "description": "A hex representation of the Blake2b hash of the replaced module's config.json file inside the package.",
                        "pattern": "^[0-9a-f]{64}$"
                    },
                    "share": {
                        "type": "string",
                        "title": "Blake2b hash hex of the whole replaced module's share package directory",
                        "description": "A hex representation of the Blake2b hash of the whole replaced module's share directory inside the package.",
                        "pattern": "^[0-9a-f]{64}$"
                    }
                },
                "required": [
                    "name",
                    "package"
                ]
            },
            "uniqueItems": true
        },
        "www": {
            "type": "string",
            "title": "Blake2b hash hex of the whole share package directory",
            "description": "A hex representation of the Blake2b hash of the whole share directory inside the package.",
            "pattern": "^[0-9a-f]{64}$"
        },
        "share": {
            "type": "string",
            "title": "Blake2b hash hex of the whole share package directory",
            "description": "A hex representation of the Blake2b hash of the whole share directory inside the package.",
            "pattern": "^[0-9a-f]{64}$"
        }
    },
    "required": [
        "metadata",
        "icon"
    ]
}

=== input-output-hk/hermes/hermes/schemas/example/hermes_app_cose_author_payload.json
{
    "metadata": "0e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8",
    "icon": "92cdf578c47085a5992256f0dcf97d0b19f1f1c9de4d5fe30c3ace6191b6e5db",
    "modules": [
        {
            "name": "module_1",
            "package": "31237cdb79ae1dfa7ffb87cde7ea8a80352d300ee5ac758a6cddd19d671925ec",
            "config": "581348337b0f3e148620173daaa5f94d00d881705dcbf0aa83efdaba61d2ede1",
            "share": "eb8649214997574e20c464388a172420d25403682bbbb80c496831c8cc1f8f0d"
        }
    ],
    "share": "70b201352f24bf1c9770b99f8f71201821411cf414377c9b8c2dbcee61db87d6",
    "www": "7bee3bbfb37286d6a41378082e08c12af0084f0b1b92f77983f4c3394e91b5e9"
}
